/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kr.or.yi.gradle_mybatis_c3p0;

import org.junit.Test;

import kr.or.yi.gradle_mybatis_c3p0.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
